# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ 'latest' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install libversion
        run: |
          ( cd /tmp
            sudo apt-get install cmake
            wget -qO- https://github.com/repology/libversion/archive/master.tar.gz | tar -xzf-
            cd libversion-master
            cmake .
            cmake --build .
            sudo cmake --install .
            sudo ldconfig )
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm Module::Install
      - run: cpanm -n --installdeps .
      - run: make
      - run: prove -bv t
